name: oiti_liveness2d
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/images/

  plugin:
    platforms:
      android:
        package: com.example.oiti_liveness2d
        pluginClass: OitiLiveness2dPlugin
      ios:
        pluginClass: OitiLiveness2dPlugin
